"""Markdown export — assembles the full manuscript from ResearchState."""

from __future__ import annotations

import datetime
import logging
from pathlib import Path
from typing import Any

from bioagent.state.schema import ResearchState

logger = logging.getLogger(__name__)

# Ordered section sequence for the manuscript
SECTION_ORDER = ["abstract", "introduction", "methods", "results", "discussion"]


def export_markdown(
    state: ResearchState,
    output_dir: Path,
    filename: str = "manuscript.md",
) -> Path:
    """Assemble the manuscript from state and write it as a Markdown file.

    Parameters
    ----------
    state : ResearchState
        Complete research state containing paper_sections, figures, references.
    output_dir : Path
        Directory to write the output file.
    filename : str
        Output filename (default: ``manuscript.md``).

    Returns
    -------
    Path
        Path to the written Markdown file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / filename

    topic = state.get("research_topic", "Untitled Research")
    question = state.get("research_question", "")
    hypothesis = state.get("selected_hypothesis", {})
    paper_sections = state.get("paper_sections", {})
    figures = state.get("figures", [])
    papers = state.get("papers", [])
    references = state.get("references", [])
    review_feedback = state.get("review_feedback", [])

    h_text = hypothesis.get("text", "") if isinstance(hypothesis, dict) else str(hypothesis or "")

    lines: list[str] = []

    # ── Front matter ──────────────────────────────────────────────────────────
    lines.append(f"# {topic}")
    lines.append("")
    today = datetime.date.today().isoformat()
    lines.append(f"*Generated by BioAgent · {today}*")
    lines.append("")

    if question:
        lines.append(f"**Research Question:** {question}")
        lines.append("")

    if h_text:
        lines.append(f"**Hypothesis:** {h_text}")
        lines.append("")

    lines.append("---")
    lines.append("")

    # ── Paper sections ─────────────────────────────────────────────────────────
    for section_key in SECTION_ORDER:
        section_data = paper_sections.get(section_key)
        if not section_data:
            continue

        content = (
            section_data.get("content", "")
            if isinstance(section_data, dict)
            else str(section_data)
        )
        if not content.strip():
            continue

        heading = section_key.title()
        lines.append(f"## {heading}")
        lines.append("")
        lines.append(content.strip())
        lines.append("")

    # Any extra sections not in the standard order
    for key, val in paper_sections.items():
        if key in SECTION_ORDER:
            continue
        content = val.get("content", "") if isinstance(val, dict) else str(val)
        if content.strip():
            lines.append(f"## {key.title()}")
            lines.append("")
            lines.append(content.strip())
            lines.append("")

    # ── Figures ────────────────────────────────────────────────────────────────
    if figures:
        lines.append("## Figures")
        lines.append("")
        for i, fig in enumerate(figures, 1):
            if not isinstance(fig, dict):
                continue
            fig_path = fig.get("path", "")
            caption = fig.get("caption", "") or fig.get("title", f"Figure {i}")
            fig_type = fig.get("type", "")

            lines.append(f"**Figure {i}.** {caption}")
            if fig_type:
                lines.append(f"*Type: {fig_type}*")
            if fig_path:
                # Emit a relative Markdown image link if path is a PNG
                if fig_path.endswith(".png"):
                    lines.append(f"![Figure {i}]({fig_path})")
                else:
                    lines.append(f"*File: `{fig_path}`*")
            lines.append("")

    # ── References ─────────────────────────────────────────────────────────────
    all_refs = references or []
    if not all_refs and papers:
        all_refs = papers  # fall back to papers list if references not populated

    if all_refs:
        lines.append("## References")
        lines.append("")
        for i, ref in enumerate(all_refs[:50], 1):
            if not isinstance(ref, dict):
                continue
            pmid = ref.get("id", "")
            title = ref.get("title", "Untitled")
            authors = ref.get("authors", "")
            journal = ref.get("journal", "")
            year = ref.get("year", "")

            parts = []
            if authors:
                parts.append(authors)
            if title:
                parts.append(f"**{title}**")
            if journal:
                parts.append(f"*{journal}*")
            if year:
                parts.append(f"({year})")
            if pmid:
                parts.append(f"PMID: {pmid}")

            lines.append(f"{i}. " + " · ".join(parts))

        lines.append("")

    # ── Review summary ─────────────────────────────────────────────────────────
    if review_feedback:
        latest = review_feedback[-1] if isinstance(review_feedback, list) else review_feedback
        if isinstance(latest, dict):
            score = latest.get("score", "N/A")
            rec = latest.get("recommendation", "")
            lines.append("---")
            lines.append("")
            lines.append(f"*Self-review score: {score}/10 · {rec}*")
            lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Manuscript exported to %s", out_path)
    return out_path
